### ISSUE TITLE
400 Bad Rquest on registration

### ISSUE THREAD

**Issue by hpk42** [fschulze/certsling#4]
Working around #3 by sym-linking ``/etc/ssl`` to ``/usr/local/etc/openssl`` and running lets-encrypt i get this error now:
```
letsencrypt-remote -r -s pytest.org doc.ptyest.org www.pytest.org docs.pytest.org 
Using existing private user key 'user.key'.
Using existing public user key 'user.pub'.
Using existing key 'pytest.org/pytest.org.key'.
Unlinking existing csr 'pytest.org/pytest.org.csr'.
Generating csr 'pytest.org/pytest.org-20161107.csr'.
Linking csr 'pytest.org/pytest.org-20161107.csr'.
verify OK
Unlinking existing der 'pytest.org/pytest.org.der'.
Generating der 'pytest.org/pytest.org-20161107.der'.
Linking der 'pytest.org/pytest.org-20161107.der'.
Generating crt 'pytest.org/pytest.org-20161107.crt'.
Starting http server on localhost:8080
Starting dns server on localhost:8053
Checking registration at letsencrypt.
Writing registration info 'registration.json'.
Got unknown status during registration: 400 Bad Request
```

**Comment by fschulze** [comment]
I now include the returned json, if there is any, in the error output. I hope this gives us further info. I suspect that it's related to the terms of use.

**Comment by hpk42** [comment]
i tried it and get an string-formatting problem because there are two `%s` but three args. When i fix this locally i get:

```
Got unknown status during registration: 400 Bad Request
:{
    "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf]",
    "status": 400,
    "type": "urn:acme:error:malformed"
}
```

**Comment by hpk42** [comment]
I'd be fine with always accepting the newest TOS, maybe letsencrypt-remote could read the error and use the provided URL to re-submit, reporting this fact to the terminal?   If need be, there could be an extra option but i am fine with just getting the info on which agreement is used.

**Comment by fschulze** [comment]
I'm trying to do that. The docs say it should be in the headers. The staging server doesn't allow to unregister (or I don't find it), so I can't properly test.

**Comment by fschulze** [comment]
You should now be able to use `--upgrade-registration` to agree to the terms of use using current master.

**Comment by hpk42** [comment]
it works, thanks!   But the option name i don't get.  It asks me for agreeing to something so i'd rather like to have `--auto-agree` or `-y` or something.

**Comment by fschulze** [comment]
You probably wouldn't have needed the option at all in your case, because the registration failed. During my testing I had a partial registration which had to be updated.

A `-y` option is something I'm considering as well.

**Comment by fschulze** [comment]
The ``-y`` option was added with 0.9.0.
