### ISSUE TITLE
option to disable HTTP challenge?

### ISSUE THREAD

**Issue by bryanlarsen** [fschulze/certsling#8]
I happen to have something running on port 8080 on the server I want to use certsling on.   That should be OK, because I want to use the DNS challenge, but certsling errors out `OSError: [Errno 98] Address already in use` before it gets a chance.

I got it working by removing 'http-01' from the list on line 767, but the option might be useful to others.   At the very least it will run faster if you disable HTTP when you know it's going to fail.

Edit:  no, that wasn't sufficient.  It still starts the HTTP server even if you remove the challenge.   I "fixed" this by changing the HTTP port number away from 8080.

**Comment by fschulze** [comment]
I'll look into adding an option to disable the http challenge and only start the necessary servers, as well as an option to change the port.

Out of curiosity, why are you running certsling on the server? It's meant to be run on your laptop (or a separate server) and the port be forwarded.

**Comment by bryanlarsen** [comment]
Even if I was running locally, I can't forward a port that's already being used.

I'm running on the server because then I can put it into cron.   From there I'm copying the cert into a vagrant provisioning script.   I suppose that I could use a different acme client, but the instructions I started with used certsimple.   And it works great!

**Comment by fschulze** [comment]
With 0.9.0 the http challenge can be disabled and only servers for enabled challenges are started.
